[package]
name = "fsverify"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structsy="0.3"
structsy-derive="0.3"